from config import db, cursor

def create_tables():
    '''Creates tables in database'''

    # main user info
    cursor.execute('''CREATE TABLE IF NOT EXISTS users(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT,
        username VARCHAR(50),
        first_name VARCHAR(70),
        last_name VARCHAR(70),
        chat_id BIGINT)''')
    db.commit()

    # our categories
    cursor.execute('''CREATE TABLE IF NOT EXISTS categories(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(100) NOT NULL)''')
    db.commit()

    # Our sweet products :D
    cursor.execute('''CREATE TABLE IF NOT EXISTS products(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_name VARCHAR(100),
        price MONEY,
        priceMaxDisсount MONEY,
        category INTEGER,
        description VARCHAR(5000))''')
    db.commit()

    cursor.execute('''CREATE TABLE IF NOT EXISTS admin(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        admin_id BIGINT,
        admin_name VARCHAR(70),
        level SMALLINT)''')
    db.commit()


    cursor.execute('''CREATE TABLE IF NOT EXISTS shop_basket(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT,
        product_id INT,
        cost MONEY)''')
    db.commit()


    cursor.execute('''CREATE TABLE IF NOT EXISTS user_logins(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT,
        login VARCHAR(100),
        password VARCHAR(150),
        product_name VARCHAR(100))''')
    db.commit()